In [1]:
import pandas as pd
import os

In [3]:
data = {
    "Employee_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Arjun","Priya","Rahul","Sneha","Amit","Kavya","Rohan","Neha","Vikas","Anjali"],
    "Department": ["IT","HR","Finance","IT","Sales","HR","Finance","Sales","IT","Finance"],
    "City": ["Hyderabad","Bengaluru","Chennai","Delhi","Mumbai","Hyderabad","Pune","Delhi","Mumbai","Chennai"],
    "Experience": [2,5,4,3,6,7,5,4,2,6],
    "Salary": [45000,65000,60000,50000,70000,75000,62000,68000,48000,64000]
}

df = pd.DataFrame(data)

df

   Employee_ID    Name Department       City  Experience  Salary
0          101   Arjun         IT  Hyderabad           2   45000
1          102   Priya         HR  Bengaluru           5   65000
2          103   Rahul    Finance    Chennai           4   60000
3          104   Sneha         IT      Delhi           3   50000
4          105    Amit      Sales     Mumbai           6   70000
5          106   Kavya         HR  Hyderabad           7   75000
6          107   Rohan    Finance       Pune           5   62000
7          108    Neha      Sales      Delhi           4   68000
8          109   Vikas         IT     Mumbai           2   48000
9          110  Anjali    Finance    Chennai           6   64000

In [4]:
print("Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nFirst 10 Rows:")
df.head(10)

Shape: (10, 6)

Data Types:
Employee_ID     int64
Name           object
Department     object
City           object
Experience      int64
Salary          int64
dtype: object

First 10 Rows:

   Employee_ID    Name Department       City  Experience  Salary
0          101   Arjun         IT  Hyderabad           2   45000
1          102   Priya         HR  Bengaluru           5   65000
2          103   Rahul    Finance    Chennai           4   60000
3          104   Sneha         IT      Delhi           3   50000
4          105    Amit      Sales     Mumbai           6   70000
5          106   Kavya         HR  Hyderabad           7   75000
6          107   Rohan    Finance       Pune           5   62000
7          108    Neha      Sales      Delhi           4   68000
8          109   Vikas         IT     Mumbai           2   48000
9          110  Anjali    Finance    Chennai           6   64000

In [5]:
# Filter employees with salary above 60000

filtered_df = df[df["Salary"] > 60000]

print("Filtered Data:")
display(filtered_df)


# Group employees by department and calculate average salary

group_df = df.groupby("Department")["Salary"].mean().reset_index()

print("Department-wise Average Salary:")
display(group_df)

Filtered Data:

   Employee_ID    Name Department       City  Experience  Salary
1          102   Priya         HR  Bengaluru           5   65000
4          105    Amit      Sales     Mumbai           6   70000
5          106   Kavya         HR  Hyderabad           7   75000
6          107   Rohan    Finance       Pune           5   62000
7          108    Neha      Sales      Delhi           4   68000
9          110  Anjali    Finance    Chennai           6   64000

Department-wise Average Salary:

  Department        Salary
0    Finance  62000.000000
1         HR  70000.000000
2         IT  47666.666667
3      Sales  69000.000000

In [6]:
# Creating department manager dataset

manager_df = pd.DataFrame({
    "Department": ["IT","HR","Finance","Sales"],
    "Manager": ["Rajesh","Suman","Kiran","Meena"]
})


# Merge employee data with manager data

merged_df = pd.merge(df, manager_df, on="Department")

merged_df

   Employee_ID    Name Department       City  Experience  Salary Manager
0          101   Arjun         IT  Hyderabad           2   45000  Rajesh
1          102   Priya         HR  Bengaluru           5   65000   Suman
2          103   Rahul    Finance    Chennai           4   60000   Kiran
3          104   Sneha         IT      Delhi           3   50000  Rajesh
4          105    Amit      Sales     Mumbai           6   70000   Meena
5          106   Kavya         HR  Hyderabad           7   75000   Suman
6          107   Rohan    Finance       Pune           5   62000   Kiran
7          108    Neha      Sales      Delhi           4   68000   Meena
8          109   Vikas         IT     Mumbai           2   48000  Rajesh
9          110  Anjali    Finance    Chennai           6   64000   Kiran

In [7]:
# Department and city wise average salary

pivot_df = pd.pivot_table(
    df,
    values="Salary",
    index="City",
    columns="Department",
    aggfunc="mean"
)

pivot_df

Department  Finance       HR       IT    Sales
City
Bengaluru       NaN  65000.0      NaN      NaN
Chennai     62000.0      NaN      NaN      NaN
Delhi           NaN      NaN  50000.0  68000.0
Hyderabad       NaN  75000.0  45000.0      NaN
Mumbai          NaN      NaN  48000.0  70000.0
Pune        62000.0      NaN      NaN      NaN

In [8]:
# Export files

df.to_csv("cleaned_employee.csv", index=False)

df.to_parquet("cleaned_employee.parquet", index=False)


# Compare file sizes

csv_size = os.path.getsize("cleaned_employee.csv")

parquet_size = os.path.getsize("cleaned_employee.parquet")


print("CSV File Size:", csv_size, "bytes")

print("Parquet File Size:", parquet_size, "bytes")

CSV File Size: 358 bytes
Parquet File Size: 4078 bytes

In [ ]:
## Observation

- Loaded and analyzed the Indian employee dataset using Pandas DataFrame.
- Checked dataset shape, column data types, and displayed the first 10 records.
- Applied filtering to extract employees based on salary conditions.
- Used GroupBy to calculate department-wise average salary.
- Performed Merge operation to combine employee data with department manager details.
- Created a Pivot Table to summarize salary distribution across departments and cities.
- Exported the cleaned dataset into CSV and Parquet formats.
- Compared file sizes of CSV and Parquet files and observed the difference in storage formats.

Conclusion:
Pandas provides efficient tools for data manipulation, aggregation, joining, and exporting datasets. These operations are useful for preparing data before analysis and machine learning workflows.