In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.feature_selection import SelectKBest, f_classif

In [2]:
data = {
    "Employee_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Arjun","Priya","Rahul","Sneha","Amit","Kavya","Rohan","Neha","Vikas","Anjali"],
    "Department": ["IT","HR","Finance","IT","Sales","HR","Finance","Sales","IT","Finance"],
    "City": ["Hyderabad","Bengaluru","Chennai","Delhi","Mumbai","Hyderabad","Pune","Delhi","Mumbai","Chennai"],
    "Education": ["B.Tech","MBA","M.Com","B.Tech","MBA","MBA","M.Com","MBA","B.Tech","M.Com"],
    "Experience": [2,5,4,3,6,7,5,4,2,6],
    "Salary": [45000,65000,60000,50000,70000,75000,62000,68000,48000,64000],
    "Performance": ["Good","Excellent","Good","Average","Excellent","Excellent","Good","Average","Good","Excellent"]
}

df = pd.DataFrame(data)

df

,Employee_ID,Name,Department,City,Education,Experience,Salary,Performance
0,101,Arjun,IT,Hyderabad,B.Tech,2,45000,Good
1,102,Priya,HR,Bengaluru,MBA,5,65000,Excellent
2,103,Rahul,Finance,Chennai,M.Com,4,60000,Good
3,104,Sneha,IT,Delhi,B.Tech,3,50000,Average
4,105,Amit,Sales,Mumbai,MBA,6,70000,Excellent
5,106,Kavya,HR,Hyderabad,MBA,7,75000,Excellent
6,107,Rohan,Finance,Pune,M.Com,5,62000,Good
7,108,Neha,Sales,Delhi,MBA,4,68000,Average
8,109,Vikas,IT,Mumbai,B.Tech,2,48000,Good
9,110,Anjali,Finance,Chennai,M.Com,6,64000,Excellent

In [3]:
df.to_csv("indian_employee_dataset.csv", index=False)

print("Dataset saved successfully.")

Dataset saved successfully.

In [4]:
df = pd.read_csv("indian_employee_dataset.csv")

df.head()

,Employee_ID,Name,Department,City,Education,Experience,Salary,Performance
0,101,Arjun,IT,Hyderabad,B.Tech,2,45000,Good
1,102,Priya,HR,Bengaluru,MBA,5,65000,Excellent
2,103,Rahul,Finance,Chennai,M.Com,4,60000,Good
3,104,Sneha,IT,Delhi,B.Tech,3,50000,Average
4,105,Amit,Sales,Mumbai,MBA,6,70000,Excellent